version: "3.8"


# 1. 明确定义网络，使服务能通过容器名互通
networks:
  app-network:
    driver: bridge

# 2. 明确定义所有命名卷
volumes:
  redis_data:
  mysql_data:
  prometheus_data:
  grafana_data:

services:

  kafka:
    image: apache/kafka:latest
    container_name: kafka-kraft
    networks:
      - app-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-kraft:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-kraft:9093
      CLUSTER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9093:9093"

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - app-network
    environment:
      REDIS_PASSWORD: 123456
    command:
      redis-server --requirepass 123456 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/home/redis

  mysql:
    image: mysql:8
    container_name: mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-kraft:9092
    depends_on:
      - kafka_kraft


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - app-network
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus_data:/home/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    networks:
      - app-network
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

